Помощь друга
htmlacademy-javascript/2049601-kekstagram-simple-27 pull request #7
Opened 2022-11-07 18:18 UTC by ElenaS63

:boom: https://htmlacademy-javascript.github.io/2049601-kekstagram-simple-27/7/

---
:mortar_board: [Помощь друга](https://up.htmlacademy.ru/javascript/27/user/2049601/tasks/16)

2022-11-08 10:58 UTC, pavel-nyukalo requested changes

2022-11-08 10:58 UTC, pavel-niukalo commented on js/effects.js
> +const EFFECTS = [
Константы - в начало модуля

2022-11-08 10:58 UTC, pavel-nyukalo commented on js/effects.js
> +};
1. Условие всегда будет возвращать `false`, поскольку неверно передан параметр. Все методы объекта `classList` ожидают параметры без точки. В `querySelector` да, передаем с точкой (как в css) поскольку там можно искать и по тегам и по айдишникам. В `classList` все без точек (например на 64 строке у тебя верно добавляется - без точки). Поэтому из условия точку надо удалить
2. Метод `some` возвращает `true/false`, поэтому мы будем пытаться добавить класс `effects__preview--true/false`. Если я правильно понял логику, ты хочешь найти нужный эффект по `value`. В таком случае нужно использовать метод `find`. И потом после того как мы найдем, нам надо взять у найденного объекта `name` (то что нам нужно).
3. И надо еще сбрасывать классы перед добавлением, иначе они будут копиться 

![image](https://user-images.githubusercontent.com/52506235/200539787-a79f5d73-1196-444b-a58d-7539c920f21b.png)

2022-11-08 10:58 UTC, pavel-nyukalo commented on js/scale.js
> +const scaleInput = document.querySelector('.scale__control--value');
Давай еще в разметке поправим на 100%, иначе
1. Немного не соответствует, у нас картинка большая (100%), а показывается 55%

![image](https://user-images.githubusercontent.com/52506235/200540364-8cae51cc-3d0e-483d-abfd-32c6ea4fe7e8.png)

2. И из-за этого немного логика ломается (55 + 25 = 80, а не 75 как нам нужно)

2022-11-08 10:58 UTC, pavel-nyukalo commented on js/scale.js
> +  image.style.transform = `scale(${value / 100})`;
Сотку в делении тоже надо на константу заменить

2022-11-08 10:58 UTC, pavel-nyukalo commented on js/slider.js
> +  },
Поле `format` можно убрать, нам не надо

2022-11-08 10:58 UTC, pavel-nyukalo commented on index.html
> +  <script src="vendor/nouislider/nouislider.js"></script>
Так же нам надо подключить стили для слайдера

2022-11-08 10:58 UTC, pavel-nyukalo commented on js/slider.js
> +export {updateSlider};
Сейчас слайдер не инициализируется, поскольку мы отсюда экспортируем, а потом вызываем только `updateSlider`.

Я предлагаю всю логику слайдера так же переместить в `effects.js`, поскольку она тесно связана с эффектами.

Так же нам при `updateSlider` надо менять опции слайдера через `noUiSlider.updateOptions`.

Пока поправь эти моменты все, а остальное поглядим на консультации

2022-11-08 19:04 UTC, ElenaS63 commented on js/effects.js
> +};
п. 3 наверное нужно сделать проверку? сделала, но не работает вроде

2022-11-08 19:09 UTC, ElenaS63 commented on js/scale.js
> +const scaleInput = document.querySelector('.scale__control--value');
а разве на 11 строке function (value = DEFAULT_SCALE) - не должно изменять значение на 100? в разметке изменила value="100%" и поля scale__control--value - ничего не изменилось

2022-11-08 19:10 UTC, ElenaS63 commented on js/effects.js
> +};
> п. 3 наверное нужно сделать проверку? сделала, но не работает вроде
еще ошибка в консоли, про пробелы, а где там лишние пробелы?
effects.js:68 Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('effects__preview--[object Object]') contains HTML space characters, which are not valid in tokens.

2022-11-08 19:20 UTC, ElenaS63 commented on js/scale.js
> +const scaleInput = document.querySelector('.scale__control--value');
> а разве на 11 строке function (value = DEFAULT_SCALE) - не должно изменять значение на 100?

2022-11-08 19:27 UTC, ElenaS63 commented on js/slider.js
> +export {updateSlider};
noUiSlider.updateOptions вписала, но опять же не работает

2022-11-08 19:29 UTC, ElenaS63 commented on js/effects.js
> +};
п.3 - через проверку, сделала так, не работает

2022-11-09 08:36 UTC, pavel-nyukalo commented on js/effects.js
> +};
Не работает, поскольку у нас `chosenEffect` это объект, найденный в массиве.

В п.2 писал, что нам надо брать поле `name` у него, но вообще, мы можем перед добавлением класса очищать все классы при помощи `element.className = ''`

2022-11-09 09:58 UTC, pavel-nyukalo commented on js/slider.js
> +export {updateSlider};
Разберем на консультации

2022-11-10 06:39 UTC, pavel-nyukalo requested changes

2022-11-10 06:39 UTC, pavel-nyukalo commented on js/effects.js
> +  }
Заметил, что у нас при закрытии/открытии модалки классы с картинки не сбрасываются. Давай вот сюда еще добавим после сброса фильтра и сброс классов, как на 103 строчке и можно будет принимать

2022-11-11 07:13 UTC, pavel-nyukalo approved these changes

2022-11-11 07:13 UTC, merged